-- Thêm dữ liệu cho bảng posts
INSERT INTO
    `posts` (
        `title`,
        `slug`,
        `summary`,
        `content`,
        `category_id`,
        `field_id`,
        `author_id`,
        `status`,
        `published_at`,
        `created_at`,
        `updated_at`,
        `view_count`
    )
VALUES
    (
        'Hướng dẫn React Hooks cơ bản',
        'huong-dan-react-hooks',
        'Tìm hiểu về React Hooks và cách sử dụng',
        'Nội dung chi tiết về React Hooks...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Vue.js 3 Composition API',
        'vuejs-3-composition-api',
        'Tìm hiểu về Composition API trong Vue.js 3',
        'Nội dung chi tiết về Composition API...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Flutter vs React Native',
        'flutter-vs-react-native',
        'So sánh hai framework phát triển mobile',
        'Phân tích chi tiết về Flutter và React Native...',
        2,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Machine Learning cơ bản',
        'machine-learning-co-ban',
        'Giới thiệu về Machine Learning',
        'Nội dung chi tiết về Machine Learning...',
        3,
        2,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Xây dựng REST API với Node.js',
        'xay-dung-rest-api-nodejs',
        'Hướng dẫn xây dựng REST API',
        'Nội dung chi tiết về REST API...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Laravel 10 Features',
        'laravel-10-features',
        'Khám phá các tính năng mới trong Laravel 10',
        'Tổng quan về các tính năng mới trong Laravel 10...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Docker cho người mới bắt đầu',
        'docker-cho-nguoi-moi',
        'Hướng dẫn cơ bản về Docker',
        'Tìm hiểu về Docker và cách sử dụng...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Git Workflow cơ bản',
        'git-workflow-co-ban',
        'Hướng dẫn sử dụng Git trong dự án',
        'Các quy trình làm việc với Git...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Clean Code trong PHP',
        'clean-code-trong-php',
        'Các nguyên tắc viết code sạch trong PHP',
        'Hướng dẫn viết code PHP sạch và dễ bảo trì...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    ),
    (
        'Testing trong Laravel',
        'testing-trong-laravel',
        'Hướng dẫn viết test trong Laravel',
        'Các phương pháp và công cụ testing trong Laravel...',
        1,
        1,
        1,
        'published',
        NOW (),
        NOW (),
        NOW (),
        0
    );